name: "Snapclient"
version: "1.1.0"
slug: sbapclient
description: >-
  "Snapclient for Snapcast"
arch: 
  - aarch64
  - amd64
  - armv7
  - i386
audio: true
init: false

schema:
  host: str
  port: port?
options:
  host: ""
  port: 1704