name: "Snapclient"
version: "0.9.0"
slug: sbapclient
description: >-
  Snapclient for Snapcast
arch: 
  - aarch64
  - amd64
  - armv7
  - i386
audio: true
init: false

schema:
  host: str
  port: port?
options:
  host: ""
  port: 1704